####
POST http://localhost:5000/api/sendOtp HTTP/1.1
Content-Type: application/json

{
    "email":"swarnitsinha@gmail.com",
    "userName":"swarnit"
}
#####

POST http://localhost:5000/api/signIn HTTP/1.1
Content-Type: application/json

{
    "email":"swarnsinha786@gmail.com",
    "password":"123"
}
################################################################
POST http://localhost:5000/api/signUp HTTP/1.1
Content-Type: application/json

{
    "email":"dipikesh.singh.915@gmail.com",
    "username":"dipikesh",
    "password":"123"
}